query DeliveryZoneList {
    deliveryProfiles(first: 10) {
        pageInfo {
            endCursor
            hasNextPage
        }
        edges {
            node {
                id
                name
                profileLocationGroups {
                    locationGroup {
                        id
                    }
                    locationGroupZones(first: 10) {
                        edges {
                            node {
                                zone {
                                    id
                                    name
                                    countries {
                                        code {
                                            countryCode
                                            restOfWorld
                                        }
                                        provinces {
                                            name
                                            code
                                        }
                                    }
                                }
                                methodDefinitions(first: 10) {
                                    edges {
                                        node {
                                            id
                                            active
                                            description
                                            methodConditions {
                                                id
                                                field
                                                operator
                                                conditionCriteria {
                                                    __typename
                                                    ... on MoneyV2 {
                                                        amount
                                                        currencyCode
                                                    }
                                                    ... on Weight {
                                                        unit
                                                        value
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
